[package]
name = "co2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bumpalo = { version = "3.17.0", features = ["boxed", "collections"] }
unicode-ident = "1.0.18"
winnow = "0.7.7"
